// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace GolfPool.Controllers
{
    public partial class AdminController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AdminController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditPlayer()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditPlayer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditTeam()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditTeam);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateScores()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateScores);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AdminController Actions { get { return MVC.Admin; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Admin";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Admin";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ImportPlayers = "ImportPlayers";
            public readonly string ImportWorldRankings = "ImportWorldRankings";
            public readonly string CreateGroups = "CreateGroups";
            public readonly string UpdateLeaderboardSource = "UpdateLeaderboardSource";
            public readonly string EditPlayer = "EditPlayer";
            public readonly string EditTeam = "EditTeam";
            public readonly string UpdateScores = "UpdateScores";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ImportPlayers = "ImportPlayers";
            public const string ImportWorldRankings = "ImportWorldRankings";
            public const string CreateGroups = "CreateGroups";
            public const string UpdateLeaderboardSource = "UpdateLeaderboardSource";
            public const string EditPlayer = "EditPlayer";
            public const string EditTeam = "EditTeam";
            public const string UpdateScores = "UpdateScores";
        }


        static readonly ActionParamsClass_UpdateLeaderboardSource s_params_UpdateLeaderboardSource = new ActionParamsClass_UpdateLeaderboardSource();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateLeaderboardSource UpdateLeaderboardSourceParams { get { return s_params_UpdateLeaderboardSource; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateLeaderboardSource
        {
            public readonly string leaderboardSource = "leaderboardSource";
        }
        static readonly ActionParamsClass_EditPlayer s_params_EditPlayer = new ActionParamsClass_EditPlayer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditPlayer EditPlayerParams { get { return s_params_EditPlayer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditPlayer
        {
            public readonly string id = "id";
            public readonly string golfer = "golfer";
        }
        static readonly ActionParamsClass_EditTeam s_params_EditTeam = new ActionParamsClass_EditTeam();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditTeam EditTeamParams { get { return s_params_EditTeam; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditTeam
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UpdateScores s_params_UpdateScores = new ActionParamsClass_UpdateScores();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateScores UpdateScoresParams { get { return s_params_UpdateScores; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateScores
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string EditPlayer = "EditPlayer";
                public readonly string Index = "Index";
                public readonly string UpdateLeaderboardSource = "UpdateLeaderboardSource";
            }
            public readonly string EditPlayer = "~/Views/Admin/EditPlayer.cshtml";
            public readonly string Index = "~/Views/Admin/Index.cshtml";
            public readonly string UpdateLeaderboardSource = "~/Views/Admin/UpdateLeaderboardSource.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_AdminController : GolfPool.Controllers.AdminController
    {
        public T4MVC_AdminController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void ImportPlayersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ImportPlayers()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ImportPlayers);
            ImportPlayersOverride(callInfo);
            return callInfo;
        }

        partial void ImportWorldRankingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult ImportWorldRankings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ImportWorldRankings);
            ImportWorldRankingsOverride(callInfo);
            return callInfo;
        }

        partial void CreateGroupsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult CreateGroups()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreateGroups);
            CreateGroupsOverride(callInfo);
            return callInfo;
        }

        partial void UpdateLeaderboardSourceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult UpdateLeaderboardSource()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateLeaderboardSource);
            UpdateLeaderboardSourceOverride(callInfo);
            return callInfo;
        }

        partial void UpdateLeaderboardSourceOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GolfPool.Controllers.LeaderboardSourceVM leaderboardSource);

        public override System.Web.Mvc.ActionResult UpdateLeaderboardSource(GolfPool.Controllers.LeaderboardSourceVM leaderboardSource)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateLeaderboardSource);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "leaderboardSource", leaderboardSource);
            UpdateLeaderboardSourceOverride(callInfo, leaderboardSource);
            return callInfo;
        }

        partial void EditPlayerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult EditPlayer(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditPlayer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditPlayerOverride(callInfo, id);
            return callInfo;
        }

        partial void EditPlayerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, GolfPool.Models.Golfer golfer);

        public override System.Web.Mvc.ActionResult EditPlayer(GolfPool.Models.Golfer golfer)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditPlayer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "golfer", golfer);
            EditPlayerOverride(callInfo, golfer);
            return callInfo;
        }

        partial void EditTeamOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult EditTeam(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditTeam);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditTeamOverride(callInfo, id);
            return callInfo;
        }

        partial void UpdateScoresOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        public override System.Web.Mvc.ActionResult UpdateScores(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateScores);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            UpdateScoresOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
